### ISSUE TITLE
Multin lanague

### ISSUE THREAD

**Issue by hasim4040** [hAWKdv/jqKeyboard#5]
This is only support only two language English and Bulgarian.
I check CDN with this link https://cdn.jsdelivr.net/gh/hawkgs/jqKeyboard/layouts/jqk.layout.en-bg.js
where is other language like spanish or something??
can you pls upload spanish and catalan keybaord layout in cdn

Thanks

**Comment by hawkgs** [comment]
Hi, sorry for the late reply. I am not actively supporting this library nor I plan adding more languages. I assume you can just create the layout yourself based on the two given examples (English and Bulgarian).
